name: Docker

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    uses: ./.github/workflows/python-app.yml
  build:
    needs: test
    uses: smpio/github-workflows/.github/workflows/docker.yaml@master
